language: python
cache: bundler
python:
  - "3.6"
install:
  # Install the latest release of Vale:
  - wget https://github.com/errata-ai/vale/releases/download/v2.0.0-beta.2/vale_2.0.0-beta.2_Linux_64-bit.tar.gz
  - mkdir bin && tar -xvzf vale_2.0.0-beta.2_Linux_64-bit.tar.gz -C bin
  - export PATH=./bin:"$PATH"

  - bundle install --jobs=3

  - pip install yamllint
  - pip install markdata
  - pip install pyyaml
before_script:
  - yamllint -c '.yamllint.yml' JQuery
script:
  - cucumber
  - zip -r JQuery.zip JQuery -x "*.DS_Store"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: JQuery.zip
  skip_cleanup: true
  on:
    tags: true
